# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
import torch
import numpy as np

print("PyTorch version:", torch.version)
print("CUDA available:", torch.cuda.is_available())


### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
tensor_2 = torch.rand((7,7))
print("2) tensor_2 shape:", tensor_2.shape)
print(tensor_2)




### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
tensor_3_b = torch.rand((1,7))
tensor_3_b_t = tensor_3_b.T
matmul_3 = tensor_2 @ tensor_3_b_t
print("3) Result shape:", matmul_3.shape)
print(matmul_3)


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
torch.manual_seed(0)
tensor_4 = torch.rand((7,7))
tensor_4_b = torch.rand((1,7))
tensor_4_b_t = tensor_4_b.T
matmul_4 = tensor_4 @ tensor_4_b_t
print("4) After manual seed(0):")
print(tensor_4)
print(tensor_4_b)
print(matmul_4)




### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
torch.manual_seed(0)
cpu_rand1 = torch.rand(3)
torch.manual_seed(0)
cpu_rand2 = torch.rand(3)
print("5) Equal after same seed:", torch.equal(cpu_rand1, cpu_rand2))

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)
    cuda_rand1 = torch.cuda.FloatTensor(3).uniform_()
    torch.cuda.manual_seed_all(0)
    cuda_rand2 = torch.cuda.FloatTensor(3).uniform_()
    print("CUDA equal after same seed:", torch.equal(cuda_rand1.cpu(), cuda_rand2.cpu()))
else:
    print("CUDA not available.")



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
A = torch.rand((3,2), device=device)
B = torch.rand((2,3), device=device)
print("6) device:", device)
print("A:", A)
print("B:", B)




### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
matmul_7 = A @ B
print("7) matmul result:", matmul_7)


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
print("8) max:", matmul_7.max().item(), "min:", matmul_7.min().item())


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
flat_argmax = torch.argmax(matmul_7)
flat_argmin = torch.argmin(matmul_7)
rows, cols = matmul_7.shape
argmax_pos = (flat_argmax // cols, flat_argmax % cols)
argmin_pos = (flat_argmin // cols, flat_argmin % cols)
print("9) argmax:", argmax_pos, "argmin:", argmin_pos)





### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
torch.manual_seed(42)
t10 = torch.rand((1,1,1,10))
t10_transposed = t10.permute(0,1,3,2)
t10_squeezed = t10_transposed.squeeze()
print("10) t10 shapes:", t10.shape, "->", t10_transposed.shape, "->", t10_squeezed.shape)
print("t10_squeezed:", t10_squeezed)